from dataclasses import dataclass
from typing import List, Dict

# Canonical atoms (you can enrich with more granular atoms)
CANONICAL_ATOMS = [
    "explosion", "sudden bright burst / intense spherical flash (bright core, star‑like bloom).",
                "debris/shrapnel/dust visibly flying outward from a central point in this frame.",
                "expanding circular dust front / pressure‑pattern ring from a center.",
                "multiple new ignitions starting near the same central origin.",
                "windows/panels actively shattering outward; shards moving away from a source.",
                "blown‑out windows/doors or facade peeled outward toward a center.",
                "crater/scorched epicenter with surrounding debris field.",
                "objects/people visibly thrown or falling away from a central point.",
                "large mushroom‑like smoke cloud consistent with a recent blast.",
                "vehicle/building panels torn outward with a dense, fresh soot/smoke plume.",
                "multiple new fires near the same origin without a visible flash in this frame.",
    "fighting", "hand/arm making contact with a person, with visible impact or target reaction.",
                "leg/knee visibly making contact with a person.",
                "hands gripping clothing/limbs/neck; one person pinning or lifting another.",
                "forceful shove that visibly displaces the other person’s body.",
                "a handheld object used to strike a person (not merely held).",
                "raised fists/wind‑up posture at close range facing another person.",
                "a person falling/stumbling/on ground while others advance toward them.",
                "clothing/hair being pulled or visible pain reaction during a scuffle.",
                "bystanders/security stepping in with urgent gestures to separate people.",
                "an object mid‑air toward a person or fresh scattered items from a scuffle.",
                "multiple people converging on one person in a way suggesting conflict.",
    "shooting", "sudden burst of light from the end of a moving object.",
                "small object rapidly propelled into the air, spinning/tumbling.",
                "plume/puff of gas or smoke emerging from the end of a moving object.",
                "a mechanical component snapping/moving backward quickly.",
                "person’s shoulders/body visibly recoiling while holding an object.",
                "dust/debris appearing on a surface as if struck.",
                "small flash in the background suggesting a distant source.",
                "thin glowing streaks moving in a straight line.",
                "fresh spark/reaction on a surface.",
                "person visibly reacting to a sudden impact/force on their body.",
                "multiple people holding/aiming objects while new impacts appear elsewhere.",
                "fresh holes/new damage to surfaces (walls, glass, panels).",
    "abuse", "strike (hand/arm/leg/knee/elbow) makes contact; visible impact or target reaction.",
             "hands/arm around neck/throat or visible pressure on airway.",
             "person restrained/pinned (e.g., pressed to wall/floor/furniture) preventing movement.",
             "hair pulled in contact, or person dragged by limb/clothing.",
             "close‑range object directed at a person (pointing with proximity) or used to hit.",
             "arms shielding head/face; recoiling/cowering from another person.",
             "one person looming/towering; other cornered or trapped against a surface.",
             "fresh visible injury or impact puff on/near body in this frame.",
             "person yanked/pulled without visible consent; loss of balance/stumbling.",
             "object mid‑air toward a person or fresh breakage targeting them.",
             "hands up, shielding self or another individual.",
             "multiple people advancing toward a single person.",
    "riot", "people visibly pushing/striking or shield‑to‑person contact with security/protective personnel.",
            "rocks/bottles/fireworks visibly airborne toward people/vehicles/buildings.",
            "breaking windows/doors or overturning objects in this frame.",
            "people removing goods from a visibly damaged storefront.",
            "a person igniting objects/vehicles; fresh flames beginning near an origin.",
            "broken glazing/doors with glass scattered.",
            "vehicles visibly damaged/overturned/on fire.",
            "large fire/smoke cloud in a street scene where a crowd is visible.",
            "makeshift barricades (furniture/shields/fences) spanning a route.",
            "people carrying sticks/bricks/umbrella‑shields, etc.",
            "people rushing/charging with tense body language; others fleeing.",
            "debris and signage damage consistent with recent unrest.",
    "car_accident", "two vehicles (or vehicle + object like pole/guardrail/wall) in contact at an impact point with fresh deformation at that contact.",
                    "parts/glass/dust flying or newly displaced from the impact point.",
                    "airbag inflating in this frame (expanding fabric).",
                    "skid marks ending at the impact point plus visible motion blur on a vehicle.",
                    "a vehicle actively striking an object with new visible deformation (e.g., crumple/shattered light) at the strike point.",
                    "crumpled hood/bumper/door and loose parts/shattered glass on the road nearby.",
                    "airbag already deployed and static (not inflating).",
                    "smoke/steam or fluid leak from a vehicle.",
                    "vehicles stopped in abnormal orientations/locations (crosswise, on median, off‑road).",
                    "skid marks near damaged vehicles but no clear motion blur.",
                    "fresh mark on pole/guardrail/wall with debris around it.",
                    "emergency responders/cones/hazard lights and visible damage in scene."
]

# Map canonical **events** (6) to a subset of atoms that can support them
EVENTS = ["explosion", "fighting", "shooting", "abuse", "riot", "car_accident"]

EVENT2ATOMS = {
        "explosion": ["sudden bright burst / intense spherical flash (bright core, star‑like bloom).",
                "debris/shrapnel/dust visibly flying outward from a central point in this frame.",
                "expanding circular dust front / pressure‑pattern ring from a center.",
                "multiple new ignitions starting near the same central origin.",
                "windows/panels actively shattering outward; shards moving away from a source.",
                "blown‑out windows/doors or facade peeled outward toward a center.",
                "crater/scorched epicenter with surrounding debris field.",
                "objects/people visibly thrown or falling away from a central point.",
                "large mushroom‑like smoke cloud consistent with a recent blast.",
                "vehicle/building panels torn outward with a dense, fresh soot/smoke plume.",
                "multiple new fires near the same origin without a visible flash in this frame."],
    "fighting": ["hand/arm making contact with a person, with visible impact or target reaction.",
                "leg/knee visibly making contact with a person.",
                "hands gripping clothing/limbs/neck; one person pinning or lifting another.",
                "forceful shove that visibly displaces the other person’s body.",
                "a handheld object used to strike a person (not merely held).",
                "raised fists/wind‑up posture at close range facing another person.",
                "a person falling/stumbling/on ground while others advance toward them.",
                "clothing/hair being pulled or visible pain reaction during a scuffle.",
                "bystanders/security stepping in with urgent gestures to separate people.",
                "an object mid‑air toward a person or fresh scattered items from a scuffle.",
                "multiple people converging on one person in a way suggesting conflict."],
    "shooting": ["sudden burst of light from the end of a moving object.",
                "small object rapidly propelled into the air, spinning/tumbling.",
                "plume/puff of gas or smoke emerging from the end of a moving object.",
                "a mechanical component snapping/moving backward quickly.",
                "person’s shoulders/body visibly recoiling while holding an object.",
                "dust/debris appearing on a surface as if struck.",
                "small flash in the background suggesting a distant source.",
                "thin glowing streaks moving in a straight line.",
                "fresh spark/reaction on a surface.",
                "person visibly reacting to a sudden impact/force on their body.",
                "multiple people holding/aiming objects while new impacts appear elsewhere.",
                "fresh holes/new damage to surfaces (walls, glass, panels)."],
    "abuse": ["strike (hand/arm/leg/knee/elbow) makes contact; visible impact or target reaction.",
             "hands/arm around neck/throat or visible pressure on airway.",
             "person restrained/pinned (e.g., pressed to wall/floor/furniture) preventing movement.",
             "hair pulled in contact, or person dragged by limb/clothing.",
             "close‑range object directed at a person (pointing with proximity) or used to hit.",
             "arms shielding head/face; recoiling/cowering from another person.",
             "one person looming/towering; other cornered or trapped against a surface.",
             "fresh visible injury or impact puff on/near body in this frame.",
             "person yanked/pulled without visible consent; loss of balance/stumbling.",
             "object mid‑air toward a person or fresh breakage targeting them.",
             "hands up, shielding self or another individual.",
             "multiple people advancing toward a single person."],
    "riot": ["people visibly pushing/striking or shield‑to‑person contact with security/protective personnel.",
            "rocks/bottles/fireworks visibly airborne toward people/vehicles/buildings.",
            "breaking windows/doors or overturning objects in this frame.",
            "people removing goods from a visibly damaged storefront.",
            "a person igniting objects/vehicles; fresh flames beginning near an origin.",
            "broken glazing/doors with glass scattered.",
            "vehicles visibly damaged/overturned/on fire.",
            "large fire/smoke cloud in a street scene where a crowd is visible.",
            "makeshift barricades (furniture/shields/fences) spanning a route.",
            "people carrying sticks/bricks/umbrella‑shields, etc.",
            "people rushing/charging with tense body language; others fleeing.",
            "debris and signage damage consistent with recent unrest."],
    "car_accident": ["two vehicles (or vehicle + object like pole/guardrail/wall) in contact at an impact point with fresh deformation at that contact.",
                    "parts/glass/dust flying or newly displaced from the impact point.",
                    "airbag inflating in this frame (expanding fabric).",
                    "skid marks ending at the impact point plus visible motion blur on a vehicle.",
                    "a vehicle actively striking an object with new visible deformation (e.g., crumple/shattered light) at the strike point.",
                    "crumpled hood/bumper/door and loose parts/shattered glass on the road nearby.",
                    "airbag already deployed and static (not inflating).",
                    "smoke/steam or fluid leak from a vehicle.",
                    "vehicles stopped in abnormal orientations/locations (crosswise, on median, off‑road).",
                    "skid marks near damaged vehicles but no clear motion blur.",
                    "fresh mark on pole/guardrail/wall with debris around it.",
                    "emergency responders/cones/hazard lights and visible damage in scene."]
}

# Atoms that **resemble** anomalies (counter-like cues), not by themselves confirming
AMBI_ENT_ATOMS = [
    "crowd running", "police lights", "smoke without fire", "people holding guns",
    "toy gun", "sparks", "backfire", "traffic jam", "people shouting"
]

ALL_ATOMS: List[str] = sorted(set(CANONICAL_ATOMS + AMBI_ENT_ATOMS))

def text_templates_for_atom(atom: str) -> List[str]:
    # Simple templates; expand as needed
    base = [
        f"a photo of {atom}",
        f"an image showing {atom}",
        f"scene with {atom} visible",
    ]
    return base
